import '../models/recipe.dart';

class RecipeService {
  // Sample recipes - In a real app, this would come from a database/API
  static List<Recipe> getAllRecipes() {
    return [
      Recipe(
        id: '1',
        name: 'Spaghetti Carbonara',
        description: 'Classic Italian pasta with creamy egg sauce, bacon, and parmesan.',
        imagePath: 'assets/images/recipes/carbonara.jpg',
        difficulty: 'Medium',
        prepTime: 10,
        cookTime: 20,
        ingredients: [
          '400g spaghetti',
          '200g bacon or pancetta',
          '4 eggs',
          '100g parmesan cheese',
          'Black pepper',
          'Salt',
        ],
        steps: [
          RecipeStep(
            title: 'Boil Water',
            description: 'Bring a large pot of salted water to a boil.',
            duration: 300,
          ),
          RecipeStep(
            title: 'Cook Pasta',
            description: 'Add spaghetti and cook according to package instructions until al dente.',
            duration: 600,
          ),
          RecipeStep(
            title: 'Prepare Bacon',
            description: 'While pasta cooks, cut bacon into small pieces and fry until crispy.',
            duration: 420,
          ),
          RecipeStep(
            title: 'Mix Egg Sauce',
            description: 'In a bowl, whisk together eggs and grated parmesan cheese.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Combine',
            description: 'Drain pasta, add to bacon pan, remove from heat, then quickly mix in egg sauce.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Add black pepper to taste and serve immediately.',
            duration: 0,
          ),
        ],
        cuisines: ['Italian'],
        dietaryTypes: [],
        allergens: ['eggs', 'dairy', 'gluten'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '2',
        name: 'Buddha Bowl',
        description: 'Healthy and colorful bowl with quinoa, roasted vegetables, and tahini dressing.',
        imagePath: 'assets/images/recipes/buddha_bowl.jpg',
        difficulty: 'Easy',
        prepTime: 15,
        cookTime: 25,
        ingredients: [
          '200g quinoa',
          '1 sweet potato',
          '1 cup chickpeas',
          '2 cups kale',
          'Cherry tomatoes',
          'Avocado',
          'Tahini',
          'Lemon juice',
        ],
        steps: [
          RecipeStep(
            title: 'Cook Quinoa',
            description: 'Rinse quinoa and cook in water according to package instructions.',
            duration: 900,
          ),
          RecipeStep(
            title: 'Roast Vegetables',
            description: 'Dice sweet potato, toss with oil and spices, roast at 200°C.',
            duration: 1500,
          ),
          RecipeStep(
            title: 'Prepare Chickpeas',
            description: 'Drain and roast chickpeas with spices for 15 minutes.',
            duration: 900,
          ),
          RecipeStep(
            title: 'Make Dressing',
            description: 'Mix tahini with lemon juice, garlic, and water until smooth.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Assemble Bowl',
            description: 'Layer quinoa, vegetables, chickpeas, and fresh greens in a bowl.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Drizzle with tahini dressing and enjoy!',
            duration: 0,
          ),
        ],
        cuisines: ['Mediterranean', 'Healthy'],
        dietaryTypes: ['vegan', 'vegetarian'],
        allergens: ['sesame'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '3',
        name: 'Chicken Stir-Fry',
        description: 'Quick and flavorful Asian-inspired stir-fry with vegetables.',
        imagePath: 'assets/images/recipes/stir_fry.jpg',
        difficulty: 'Easy',
        prepTime: 15,
        cookTime: 12,
        ingredients: [
          '500g chicken breast',
          'Bell peppers',
          'Broccoli',
          'Carrots',
          'Soy sauce',
          'Ginger',
          'Garlic',
          'Rice',
        ],
        steps: [
          RecipeStep(
            title: 'Prepare Ingredients',
            description: 'Slice chicken and chop all vegetables into bite-sized pieces.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Cook Rice',
            description: 'Start cooking rice according to package instructions.',
            duration: 900,
          ),
          RecipeStep(
            title: 'Cook Chicken',
            description: 'Heat oil in a wok, add chicken and cook until golden.',
            duration: 360,
          ),
          RecipeStep(
            title: 'Add Vegetables',
            description: 'Add vegetables and stir-fry for 3-4 minutes.',
            duration: 240,
          ),
          RecipeStep(
            title: 'Add Sauce',
            description: 'Pour in soy sauce mixture and toss everything together.',
            duration: 120,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Serve hot over rice.',
            duration: 0,
          ),
        ],
        cuisines: ['Asian', 'Chinese'],
        dietaryTypes: [],
        allergens: ['soy'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '4',
        name: 'Chocolate Lava Cake',
        description: 'Decadent dessert with molten chocolate center.',
        imagePath: 'assets/images/recipes/lava_cake.jpg',
        difficulty: 'Hard',
        prepTime: 10,
        cookTime: 12,
        ingredients: [
          '100g dark chocolate',
          '100g butter',
          '2 eggs',
          '2 egg yolks',
          '50g sugar',
          '30g flour',
          'Vanilla extract',
        ],
        steps: [
          RecipeStep(
            title: 'Melt Chocolate',
            description: 'Melt chocolate and butter together in a double boiler.',
            duration: 300,
          ),
          RecipeStep(
            title: 'Mix Eggs',
            description: 'Whisk eggs, yolks, and sugar until thick and pale.',
            duration: 180,
          ),
          RecipeStep(
            title: 'Combine',
            description: 'Fold chocolate mixture into eggs, then add flour.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Prepare Ramekins',
            description: 'Butter and flour 4 ramekins, divide batter evenly.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Bake',
            description: 'Bake at 200°C for 12 minutes until edges are set.',
            duration: 720,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Let cool for 1 minute, invert onto plates, serve immediately.',
            duration: 60,
          ),
        ],
        cuisines: ['French', 'Dessert'],
        dietaryTypes: ['vegetarian'],
        allergens: ['eggs', 'dairy', 'gluten'],
        isLocked: true,
        pointsRequired: 100,
      ),
      Recipe(
        id: '5',
        name: 'Greek Salad',
        description: 'Fresh and tangy Mediterranean salad with feta cheese.',
        imagePath: 'assets/images/recipes/greek_salad.jpeg',
        difficulty: 'Easy',
        prepTime: 10,
        cookTime: 0,
        ingredients: [
          'Cucumber',
          'Tomatoes',
          'Red onion',
          'Olives',
          'Feta cheese',
          'Olive oil',
          'Lemon juice',
          'Oregano',
        ],
        steps: [
          RecipeStep(
            title: 'Chop Vegetables',
            description: 'Cut cucumber, tomatoes, and onion into bite-sized pieces.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Combine',
            description: 'Mix all vegetables in a large bowl with olives.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Add Feta',
            description: 'Crumble feta cheese over the salad.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Dress',
            description: 'Drizzle with olive oil, lemon juice, and oregano.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Toss gently and serve immediately.',
            duration: 0,
          ),
        ],
        cuisines: ['Greek', 'Mediterranean'],
        dietaryTypes: ['vegetarian'],
        allergens: ['dairy'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '6',
        name: 'Vegetable Curry',
        description: 'Aromatic Indian curry with mixed vegetables and coconut milk.',
        imagePath: 'assets/images/recipes/curry.jpg',
        difficulty: 'Medium',
        prepTime: 15,
        cookTime: 30,
        ingredients: [
          'Mixed vegetables',
          'Coconut milk',
          'Curry paste',
          'Onion',
          'Garlic',
          'Ginger',
          'Tomatoes',
          'Rice',
        ],
        steps: [
          RecipeStep(
            title: 'Sauté Base',
            description: 'Cook onion, garlic, and ginger until fragrant.',
            duration: 300,
          ),
          RecipeStep(
            title: 'Add Curry Paste',
            description: 'Stir in curry paste and cook for 1 minute.',
            duration: 60,
          ),
          RecipeStep(
            title: 'Add Vegetables',
            description: 'Add chopped vegetables and tomatoes, stir well.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Simmer',
            description: 'Pour in coconut milk and simmer for 20 minutes.',
            duration: 1200,
          ),
          RecipeStep(
            title: 'Cook Rice',
            description: 'Meanwhile, cook rice according to package.',
            duration: 900,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Serve curry over rice with fresh cilantro.',
            duration: 0,
          ),
        ],
        cuisines: ['Indian', 'Asian'],
        dietaryTypes: ['vegan', 'vegetarian'],
        allergens: [],
        isLocked: true,
        pointsRequired: 50,
      ),
      Recipe(
        id: '7',
        name: 'Beef Tacos',
        description: 'Spicy Mexican tacos with seasoned ground beef and fresh toppings.',
        imagePath: 'assets/images/recipes/beef_tacos.jpg',
        difficulty: 'Easy',
        prepTime: 10,
        cookTime: 15,
        ingredients: [
          '500g ground beef',
          'Taco shells',
          'Lettuce',
          'Tomatoes',
          'Cheese',
          'Sour cream',
          'Taco seasoning',
          'Onion',
        ],
        steps: [
          RecipeStep(
            title: 'Cook Beef',
            description: 'Brown ground beef in a large skillet over medium-high heat.',
            duration: 420,
          ),
          RecipeStep(
            title: 'Add Seasoning',
            description: 'Add taco seasoning and water, simmer for 5 minutes.',
            duration: 300,
          ),
          RecipeStep(
            title: 'Prep Toppings',
            description: 'Chop lettuce, tomatoes, and onions. Shred cheese.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Warm Shells',
            description: 'Heat taco shells according to package instructions.',
            duration: 180,
          ),
          RecipeStep(
            title: 'Assemble',
            description: 'Fill shells with beef and add your favorite toppings.',
            duration: 0,
          ),
        ],
        cuisines: ['Mexican'],
        dietaryTypes: [],
        allergens: ['dairy', 'gluten'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '8',
        name: 'Margherita Pizza',
        description: 'Classic Italian pizza with fresh mozzarella, basil, and tomato sauce.',
        imagePath: 'assets/images/recipes/margherita_pizza.webp',
        difficulty: 'Medium',
        prepTime: 20,
        cookTime: 15,
        ingredients: [
          'Pizza dough',
          '200g mozzarella',
          'Fresh basil',
          'Tomato sauce',
          'Olive oil',
          'Salt',
          'Garlic',
        ],
        steps: [
          RecipeStep(
            title: 'Preheat Oven',
            description: 'Preheat oven to 250°C (480°F) with pizza stone if available.',
            duration: 600,
          ),
          RecipeStep(
            title: 'Roll Dough',
            description: 'Roll out pizza dough on a floured surface to desired thickness.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Add Sauce',
            description: 'Spread tomato sauce evenly, leaving a border for the crust.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Add Toppings',
            description: 'Add torn mozzarella and drizzle with olive oil.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Bake',
            description: 'Bake for 12-15 minutes until crust is golden and cheese bubbles.',
            duration: 840,
          ),
          RecipeStep(
            title: 'Finish',
            description: 'Add fresh basil leaves and serve hot.',
            duration: 0,
          ),
        ],
        cuisines: ['Italian'],
        dietaryTypes: ['vegetarian'],
        allergens: ['dairy', 'gluten'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '9',
        name: 'Pad Thai',
        description: 'Thai street food classic with rice noodles, shrimp, and peanuts.',
        imagePath: 'assets/images/recipes/pad_thai.jpg',
        difficulty: 'Medium',
        prepTime: 20,
        cookTime: 15,
        ingredients: [
          '200g rice noodles',
          '300g shrimp',
          '2 eggs',
          'Bean sprouts',
          'Peanuts',
          'Lime',
          'Fish sauce',
          'Tamarind paste',
          'Green onions',
        ],
        steps: [
          RecipeStep(
            title: 'Soak Noodles',
            description: 'Soak rice noodles in warm water for 15 minutes.',
            duration: 900,
          ),
          RecipeStep(
            title: 'Prepare Sauce',
            description: 'Mix fish sauce, tamarind paste, and sugar for the sauce.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Cook Shrimp',
            description: 'Stir-fry shrimp in hot oil until pink, set aside.',
            duration: 240,
          ),
          RecipeStep(
            title: 'Scramble Eggs',
            description: 'Push shrimp aside, scramble eggs in the same pan.',
            duration: 120,
          ),
          RecipeStep(
            title: 'Combine',
            description: 'Add drained noodles and sauce, toss everything together.',
            duration: 180,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Top with bean sprouts, peanuts, lime wedges, and green onions.',
            duration: 0,
          ),
        ],
        cuisines: ['Thai', 'Asian'],
        dietaryTypes: [],
        allergens: ['shellfish', 'eggs', 'peanuts', 'fish'],
        isLocked: true,
        pointsRequired: 75,
      ),
      Recipe(
        id: '10',
        name: 'Caesar Salad',
        description: 'Crisp romaine lettuce with creamy Caesar dressing and croutons.',
        imagePath: 'assets/images/recipes/caesar_salad.jpg',
        difficulty: 'Easy',
        prepTime: 15,
        cookTime: 5,
        ingredients: [
          'Romaine lettuce',
          'Parmesan cheese',
          'Croutons',
          'Caesar dressing',
          'Lemon',
          'Garlic',
          'Anchovies (optional)',
        ],
        steps: [
          RecipeStep(
            title: 'Wash Lettuce',
            description: 'Wash and dry romaine lettuce, tear into bite-sized pieces.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Make Croutons',
            description: 'Toast bread cubes with olive oil and garlic in a pan.',
            duration: 300,
          ),
          RecipeStep(
            title: 'Prepare Dressing',
            description: 'Whisk together dressing ingredients (or use store-bought).',
            duration: 0,
          ),
          RecipeStep(
            title: 'Assemble',
            description: 'Toss lettuce with dressing in a large bowl.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Top with croutons, shaved parmesan, and black pepper.',
            duration: 0,
          ),
        ],
        cuisines: ['American'],
        dietaryTypes: ['vegetarian'],
        allergens: ['dairy', 'gluten', 'fish'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '11',
        name: 'Beef Burger',
        description: 'Juicy homemade burger with all the classic toppings.',
        imagePath: 'assets/images/recipes/beef_burger.webp',
        difficulty: 'Easy',
        prepTime: 10,
        cookTime: 12,
        ingredients: [
          '500g ground beef',
          'Burger buns',
          'Lettuce',
          'Tomato',
          'Onion',
          'Cheese slices',
          'Pickles',
          'Ketchup & mustard',
          'Salt & pepper',
        ],
        steps: [
          RecipeStep(
            title: 'Form Patties',
            description: 'Divide beef into 4 portions, form into patties, season with salt and pepper.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Heat Grill',
            description: 'Heat grill or skillet to medium-high heat.',
            duration: 300,
          ),
          RecipeStep(
            title: 'Cook Burgers',
            description: 'Grill patties for 4-5 minutes per side for medium.',
            duration: 540,
          ),
          RecipeStep(
            title: 'Add Cheese',
            description: 'Place cheese on patties in last minute of cooking.',
            duration: 60,
          ),
          RecipeStep(
            title: 'Toast Buns',
            description: 'Toast burger buns on the grill for 30 seconds.',
            duration: 30,
          ),
          RecipeStep(
            title: 'Assemble',
            description: 'Build burgers with lettuce, tomato, onion, pickles, and sauces.',
            duration: 0,
          ),
        ],
        cuisines: ['American'],
        dietaryTypes: [],
        allergens: ['dairy', 'gluten'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '12',
        name: 'Sushi Rolls',
        description: 'Fresh homemade sushi rolls with salmon and avocado.',
        imagePath: 'assets/images/recipes/sushi_rolls.webp',
        difficulty: 'Hard',
        prepTime: 30,
        cookTime: 20,
        ingredients: [
          'Sushi rice',
          'Nori sheets',
          'Fresh salmon',
          'Avocado',
          'Cucumber',
          'Rice vinegar',
          'Soy sauce',
          'Wasabi',
          'Pickled ginger',
        ],
        steps: [
          RecipeStep(
            title: 'Cook Rice',
            description: 'Cook sushi rice according to package instructions.',
            duration: 1200,
          ),
          RecipeStep(
            title: 'Season Rice',
            description: 'Mix warm rice with rice vinegar, sugar, and salt. Let cool.',
            duration: 600,
          ),
          RecipeStep(
            title: 'Prep Ingredients',
            description: 'Slice salmon, avocado, and cucumber into thin strips.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Spread Rice',
            description: 'Place nori on bamboo mat, spread rice evenly leaving 1 inch at top.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Add Fillings',
            description: 'Place salmon, avocado, and cucumber in a line across the rice.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Roll',
            description: 'Using the mat, roll tightly from bottom to top, seal with water.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Slice',
            description: 'Cut roll into 8 pieces with a sharp, wet knife.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Serve with soy sauce, wasabi, and pickled ginger.',
            duration: 0,
          ),
        ],
        cuisines: ['Japanese', 'Asian'],
        dietaryTypes: [],
        allergens: ['fish'],
        isLocked: true,
        pointsRequired: 150,
      ),
      Recipe(
        id: '13',
        name: 'Pancakes',
        description: 'Fluffy buttermilk pancakes perfect for breakfast.',
        imagePath: 'assets/images/recipes/pancakes.jpg',
        difficulty: 'Easy',
        prepTime: 10,
        cookTime: 20,
        ingredients: [
          '2 cups flour',
          '2 eggs',
          '2 cups buttermilk',
          '2 tbsp sugar',
          'Baking powder',
          'Salt',
          'Butter',
          'Maple syrup',
        ],
        steps: [
          RecipeStep(
            title: 'Mix Dry',
            description: 'Whisk together flour, sugar, baking powder, and salt.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Mix Wet',
            description: 'In another bowl, beat eggs with buttermilk and melted butter.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Combine',
            description: 'Pour wet ingredients into dry, stir until just combined (lumpy is ok!).',
            duration: 0,
          ),
          RecipeStep(
            title: 'Heat Griddle',
            description: 'Heat griddle or pan to medium heat, grease lightly.',
            duration: 180,
          ),
          RecipeStep(
            title: 'Cook Pancakes',
            description: 'Pour 1/4 cup batter per pancake, cook until bubbles form, flip.',
            duration: 240,
          ),
          RecipeStep(
            title: 'Serve',
            description: 'Stack pancakes and serve with butter and maple syrup.',
            duration: 0,
          ),
        ],
        cuisines: ['American'],
        dietaryTypes: ['vegetarian'],
        allergens: ['eggs', 'dairy', 'gluten'],
        isLocked: false,
        pointsRequired: 0,
      ),
      Recipe(
        id: '14',
        name: 'Ramen Bowl',
        description: 'Hearty Japanese noodle soup with pork and soft-boiled egg.',
        imagePath: 'assets/images/recipes/ramen_bowl.jpg',
        difficulty: 'Medium',
        prepTime: 15,
        cookTime: 25,
        ingredients: [
          'Ramen noodles',
          'Pork belly',
          'Eggs',
          'Chicken broth',
          'Soy sauce',
          'Miso paste',
          'Green onions',
          'Nori',
          'Corn',
        ],
        steps: [
          RecipeStep(
            title: 'Boil Eggs',
            description: 'Boil eggs for 6-7 minutes for soft-boiled, then ice bath.',
            duration: 420,
          ),
          RecipeStep(
            title: 'Cook Pork',
            description: 'Sear pork belly until crispy, slice into pieces.',
            duration: 480,
          ),
          RecipeStep(
            title: 'Make Broth',
            description: 'Heat chicken broth, add soy sauce and miso paste.',
            duration: 300,
          ),
          RecipeStep(
            title: 'Cook Noodles',
            description: 'Cook ramen noodles according to package instructions.',
            duration: 240,
          ),
          RecipeStep(
            title: 'Assemble',
            description: 'Place noodles in bowl, pour hot broth over.',
            duration: 0,
          ),
          RecipeStep(
            title: 'Top',
            description: 'Add pork, halved egg, green onions, nori, and corn.',
            duration: 0,
          ),
        ],
        cuisines: ['Japanese', 'Asian'],
        dietaryTypes: [],
        allergens: ['eggs', 'gluten', 'soy'],
        isLocked: true,
        pointsRequired: 80,
      ),
      Recipe(
        id: '15',
        name: 'Mushroom Risotto',
        description: 'Creamy Italian rice with earthy mushrooms and parmesan.',
        imagePath: 'assets/images/recipes/mushroom_risotto.jpg',
        difficulty: 'Hard',
        prepTime: 10,
        cookTime: 35,
        ingredients: [
          'Arborio rice',
          'Mixed mushrooms',
          'White wine',
          'Chicken stock',
          'Parmesan',
          'Butter',
          'Onion',
          'Garlic',
        ],
        steps: [
          RecipeStep(
            title: 'Sauté Mushrooms',
            description: 'Cook sliced mushrooms in butter until golden, set aside.',
            duration: 420,
          ),
          RecipeStep(
            title: 'Sauté Base',
            description: 'Cook onion and garlic until soft in the same pan.',
            duration: 300,
          ),
          RecipeStep(
            title: 'Toast Rice',
            description: 'Add rice, stir for 2 minutes until slightly translucent.',
            duration: 120,
          ),
          RecipeStep(
            title: 'Add Wine',
            description: 'Pour in wine, stir until absorbed.',
            duration: 180,
          ),
          RecipeStep(
            title: 'Add Stock',
            description: 'Add warm stock one ladle at a time, stirring constantly.',
            duration: 1200,
          ),
          RecipeStep(
            title: 'Finish',
            description: 'Stir in mushrooms, butter, and parmesan. Serve immediately.',
            duration: 0,
          ),
        ],
        cuisines: ['Italian'],
        dietaryTypes: ['vegetarian'],
        allergens: ['dairy'],
        isLocked: true,
        pointsRequired: 120,
      ),
    ];
  }

  static List<Recipe> getFilteredRecipes(
    List<Recipe> recipes,
    List<String> allergens,
    List<String> dietaryTypes,
    List<String> preferredCuisines,
  ) {
    return recipes.where((recipe) {
      // Filter out recipes with allergens
      if (allergens.isNotEmpty) {
        if (recipe.allergens.any((a) => allergens.contains(a))) {
          return false;
        }
      }

      // Filter by dietary types
      if (dietaryTypes.isNotEmpty) {
        if (!dietaryTypes.any((d) => recipe.dietaryTypes.contains(d))) {
          return false;
        }
      }

      // Filter by preferred cuisines (if any specified)
      if (preferredCuisines.isNotEmpty) {
        if (!preferredCuisines.any((c) => recipe.cuisines.contains(c))) {
          return false;
        }
      }

      return true;
    }).toList();
  }
}
